### ISSUE TITLE
Program errors after running. 

### ISSUE THREAD

**Issue by CarrotFarmering** [johnhw/sinewave_speech#1]
I literally don't know what happened.

Read TheQuickyBrownFox.wav
Traceback (most recent call last):
  File "C:\Users\Locations\ws.py", line 498, in <module>
    main(sys.argv)
  File "C:\Users\Locations\sws.py", line 458, in main
    modulated = sinethesise(
                ^^^^^^^^^^^^
  File "C:\Users\Locations\sws.py", line 283, in sinethesise
    window = scipy.signal.hann(frame_len)
             ^^^^^^^^^^^^^^^^^
AttributeError: module 'scipy.signal' has no attribute 'hann'

**Comment by danbcoop** [comment]
Replacing each occurrence of "scipy.signal.hann" with "scipy.signal.windows.hann" should fix it.
